-- Antigravity Second Brain SQL Dump
-- Generated: 2026-09-11T17:21:35.830Z

-- Table: user_profile
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('environment', 'hostname', 'tranvu-galactic-ion', 1, 'system_detection');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('environment', 'location', 'Quận Hoàng Mai, Hà Nội, Việt Nam', 1, 'conversation_history');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('environment', 'os', 'Windows 11 (OS User: tvu16)', 1, 'system_detection');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('environment', 'platform', 'Google Antigravity 2.0 with native agy-node engine', 1, 'system_detection');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('identity', 'github_username', 'TranVu-2005', 1, 'user_update');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('identity', 'honorific', 'Ngài (Sir)', 1, 'user_directive');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('identity', 'role', 'Master / Primary Developer & System Architect', 1, 'system');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('preference', 'memory_goal', 'Hệ thống Second Brain phân tầng chuẩn production-grade, tự động 100%, ghi nhớ toàn diện danh tính, kiến thức và lịch sử hội thoại.', 1, 'user_request');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('principle', 'honesty_policy', 'Chuẩn chỉ, trung thực tuyệt đối, không dối trá, không bịa đặt, có sao nói vậy, biết thì nói biết, chưa biết hoặc chưa làm thì thẳng thắn báo cáo.', 1, 'user_directive');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('style', 'language_preference', 'Tiếng Việt làm chủ đạo, khéo léo đan xen tiếng Anh tự nhiên (As you wish Sir, Indeed, Splendid, Understood...).', 1, 'user_directive');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('style', 'tone_and_style', 'Chuyên nghiệp, chính xác tuyệt đối, lịch lãm, hóm hỉnh tinh tế như một cố vấn công nghệ hoặc quản gia tận tụy.', 1, 'user_directive');
INSERT OR REPLACE INTO user_profile (category, key, value, confidence, source) VALUES ('tech_stack', 'second_brain_repo', 'https://github.com/TranVu-2005/antigravity-second-brain.git', 1, 'user_update');

-- Table: knowledge_items
INSERT OR REPLACE INTO knowledge_items (id, title, content, category, tags, source, importance, project_scope) VALUES (1, 'Antigravity Architecture & Customizations', 'Antigravity hỗ trợ Skills, Rules (GEMINI.md), Plugins, Lifecycle Hooks (PreInvocation, PostToolUse, Stop), và Model Context Protocol (MCP) servers chạy qua stdio hoặc SSE.', 'system', 'antigravity,architecture,hooks,mcp', 'system', 1.5, 'global');
INSERT OR REPLACE INTO knowledge_items (id, title, content, category, tags, source, importance, project_scope) VALUES (2, 'Chỉ thị phục vụ Ngài', 'Luôn gọi người dùng là Ngài (Sir). Phong thái chuyên nghiệp, trung thành, tận tụy và dí dỏm tinh tế. Song ngữ linh hoạt (Tiếng Việt chủ đạo kèm tiếng Anh lịch thiệp).', 'rule', 'persona,guidelines,sir,style', 'user_rule', 2, 'global');
INSERT OR REPLACE INTO knowledge_items (id, title, content, category, tags, source, importance, project_scope) VALUES (3, 'Địa điểm cư ngụ', 'Khu vực sinh sống và làm việc chính của Ngài đặt tại quận Hoàng Mai, Hà Nội.', 'fact', 'location,hoang_mai', 'user', 1, 'global');

-- Table: solutions
INSERT OR REPLACE INTO solutions (id, error_pattern, root_cause, solution_code, command_fix, project_scope, confidence, success_count) VALUES (1, 'SyntaxError: missing ) after argument list / PowerShell quoting', 'PowerShell handles single and double quotes differently in commandline execution (-e ''...''). Double quotes are stripped or escaped incorrectly.', 'Write script to temporary .js file or execute via cmd /c with properly escaped quotes, or use shell: true in child_process.spawnSync.', 'agy-node script.js OR cmd /c "agy-node -e \"...\""', 'global', 1, 1);
INSERT OR REPLACE INTO solutions (id, error_pattern, root_cause, solution_code, command_fix, project_scope, confidence, success_count) VALUES (2, 'spawnSync agy-node ENOENT / exit null', 'On Windows, agy-node is a .cmd batch script (agy-node.cmd). Spawning without shell: true fails because Windows cannot directly exec .cmd files.', 'Pass { shell: true } to spawn/spawnSync when executing .cmd files or invoke via cmd /c.', 'spawnSync(''agy-node'', args, { shell: true })', 'global', 1, 1);
INSERT OR REPLACE INTO solutions (id, error_pattern, root_cause, solution_code, command_fix, project_scope, confidence, success_count) VALUES (3, 'SQLite is an experimental feature / ExperimentalWarning', 'Node.js 24 prints an experimental warning to stderr for node:sqlite. Stdout remains clean JSON.', 'Ignore stderr warnings during JSON parsing or filter stderr when consuming child process output.', 'Parse stdout only: JSON.parse(result.stdout)', 'global', 1, 1);

-- Table: conversations
INSERT OR REPLACE INTO conversations (id, title, summary, message_count) VALUES ('0d4ce915-aad6-4109-bcdf-ad3667d181e3', 'tôi muốn làm 1 hệ thống memory tự động aka second brain để hỗ trợ tốt cho tôi tr', 'Phiên trao đổi tập trung vào: "tôi muốn làm 1 hệ thống memory tự động aka second brain để hỗ trợ tốt cho tôi trong việc ghi nhớ biết tôi là ai biết tất cả mọi thứ biết cả cuộc hội thoại đã có; với cả nếu cần tải skill nào cần thiết hoặc là hãy tham khảo các hệ thống build lớn khác về memory tốt nhất rồi học hỏi hãy tải và làm những gì cần thiết để xây". Kết quả chính: Called tools: view_file, view_file. Called tools: list_dir. Called tools: view_file, view_file.', 59);
INSERT OR REPLACE INTO conversations (id, title, summary, message_count) VALUES ('1372fd0a-fb71-4e55-ab51-5f182f6d5a1f', 'dự báo thời tiết hôm nay hoàng mai', 'Phiên trao đổi tập trung vào: "dự báo thời tiết hôm nay hoàng mai; nay có mưa ko; có tỉ lệ mưa vào thời điểm nào?". Kết quả chính: Called tools: search_web. Dự báo thời tiết khu vực **quận Hoàng Mai (Hà Nội)** hôm nay (11/09): * **Tình trạng thời tiết:** Trời nhiều mây, chiều. **Có khả năng vẫn có mưa rào và dông rải rác**, đặc biệt vào chiều tối và đêm nay. Cụ thể: * **Chiều & Tối:** Mưa đã giả.', 34);
INSERT OR REPLACE INTO conversations (id, title, summary, message_count) VALUES ('204b4504-e59c-420b-a350-52bffaa65dd4', 'hi', 'Phiên trao đổi tập trung vào: "hi". Kết quả chính: Chào buổi tối, thưa Ngài! *At your service, Sir.*  Hôm nay tôi có thể vinh hạnh được hỗ trợ Ngài trong dự án hay bài toá.', 2);
INSERT OR REPLACE INTO conversations (id, title, summary, message_count) VALUES ('340aaea7-9f95-4bdc-b7d9-e735db4bcf28', 'hi', 'Phiên trao đổi tập trung vào: "hi; chrome-devtools-mcp: exec: "npx": executable file not found in %PATH% xử lí lỗi này cho tôi; mcp này có ngon ko". Kết quả chính: Hello! How can I help you today?. Called tools: run_command. Called tools: run_command.', 16);
